bounding_box:
  - - 45.2
    - 38.6
  - - 47.6
    - 40.7
country: null
fallbackZoneMixes:
  _comment: Average carbon intensity using 2016 mean production per fuel source (100%
    hydro) and IPCC 2014 default lifecycle emission factor
  powerOriginRatios:
    value:
      hydro: 1
region: Asia
timezone: null
